### ISSUE TITLE
Boost formatting seems to not work

### ISSUE THREAD

**Issue by sdevissc** [cp3-llbb/plotIt#67]
Hi!

I did a pull of all latest changes in plotIt, which include the change of formatting of the  luminosity-label. Then in my python config file I use now 

luminosity-label: '%1$.2f fb^{-1} (13 TeV)'

as discussed in the related PR. But for some reason this is not understood by the boost parser: see for instance http://cp3.irmp.ucl.ac.be/~simon/plottest_postbugfix_SF_withSig/lljj_M_llCRbb_logy.png

I checked that the code changes related to the luminosity-label are present, and of course recompiled plotIt. Any idea about what is going wrong?

Best,

Simon

**Comment by blinkseb** [comment]
That's very _very_ strange. I tested on my side and it works as expected (and integration tests are also still working).

The only explanation is that you are still using the old code for the lumi parsing, but it'd be strange since you explicitly checked the new code is here ... Maybe some compilation errors? (as a quick check, you can try to add `%lumi%` anywhere in the string and see if it's replaced by the luminosity. If yes, you are indeed using the old code)

**Comment by sdevissc** [comment]
Ok, problem solved, that was just a mistake from my side, sorry for trouble :)
